apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app.kubernetes.io/name: proxy
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - containerPort: 80
    